// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Perfect Pitch",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Perfect Pitch",
            targets: ["AppModule"],
            bundleIdentifier: "dev.heryan.Perfect-Pitch",
            teamIdentifier: "9VBW89A4U3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
            ],
            capabilities: [
                .microphone(purposeString: "Unknown Usage Description")
            ],
            appCategory: .musicGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)